name: scan
on:
    workflow_dispatch:
jobs:
    scan:
        runs-on: [ubuntu-latest]
        steps:
        - uses: actions/checkout@master
        - name: run scan
          run: |
            gh repo list ${{ github.repository_owner }} --no-archived --json name --jq '.[].name' | while read repo; do
                docker run trufflesecurity/trufflehog github --repo "https://github.com/${{ github.repository_owner }}/$repo"
            done
          env:
            GH_TOKEN: ${{ github.token }}
